name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # change to your AWS region

      - name: Deploy express dummy server
        run: aws s3 sync . s3://dummy-dev-server --delete

      # Optional: Add deployment step if you're copying to S3, SSH into EC2, or triggering CodeDeploy, etc.
      # - name: Deploy to EC2 via SSH
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ec2-user@<EC2-PUBLIC-IP> 'bash deploy-script.sh'
      #   env:
      #     PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

